interests/interests/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from avatar import urls
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(),name='index'),
    path('mainapp/',include('mainapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('profile/',views.profile_page,name='profile'),
    path('api-auth/', include('rest_framework.urls')),
    path('avatar/',include('avatar.urls')),
    path('emoji/',include('emoji.urls')),
    path('register/',views.register,name='register'),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('tinymce/', include('tinymce.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('', include('django_private_chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interests/mainapp/urls.py
from django.urls import path,include
from . import views
from . import views as user_view
from .views import SearchResultsView,UserPostListView,PostUpdateView,PostDeleteView,PostLikeRedirect,PostLikeAPIRedirect,PostSaveRedirect,Home,PostSaveListView,get_premium,MessageInbox,CreateMessageView
from django.conf import settings
from django.conf.urls.static import static
from mainapp.forms import UserCreationForm,UserProfileInfoForms,UserUpdateForm,ProfileUpdateForm,ReplyForm
from django.contrib.auth import views as auth_views
app_name = 'mainapp'


urlpatterns = [
    path('',views.Home.as_view(),name='index'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    
    path('new/<username>/',views.CreateMessageView.as_view(),name='message-form', template_name="mainapp/message_form.html"),
    path('inbox/',views.MessageInbox.as_view(),name='inbox-list'),
    path('profile/<str:username>/',views.view_profile,name='view_profile_with_pk'),
    path('profile/',views.view_profile,name='view_profile'),
    path('posts/',views.PostListView.as_view(),name='post_list'),
    path('post_new/', views.CreatePostView.as_view(), name='post_new'),
    path('register/',user_view.register,name='register'),
    path('user_login/',auth_views.LoginView.as_view(template_name='mainapp/login.html',),name='user_login'),
    path('profile/',views.profile_page,name='profile'),
    path('account/update/',views.profile_update,name='profile_update'),
    path('posts/saved/',views.PostSaveListView.as_view(),name='saved-posts'),
    
    path('<int:pk>/<str:slug>/like', views.PostLikeRedirect.as_view(), name='post_likes'),
    path('<int:pk>/<str:slug>/save', views.PostSaveRedirect.as_view(), name='post_saves'),
    path('<int:pk>/<str:slug>/like', views.PostLikeAPIRedirect.as_view(), name='post_api_likes'),
    
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('<int:pk>/<str:slug>/publish/', views.post_publish, name='post_publish'),
    path('<str:slug>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<str:slug>/reply',views.add_reply_to_comment,name='add_reply_to_comment'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('posts_search/',views.SearchResultsView.as_view(),name='search_results'),
    path('users_search/',views.SearchResultsViewUsers.as_view(),name='search_results_user'),
    path('avatar/',include('avatar.urls')),
    path('<str:slug>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/<str:slug>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('tag/<slug>',views.TagIndexView.as_view(),name='tagged'),
    path('groups/new/',views.CreateGroup.as_view(),name='create_group'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('groups/all/',views.ListGroups.as_view(),name='groups'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave'),
    path('connect/<operation>/<pk>/<str:slug/>',views.change_friends,name='change_friends'),
    
    path('premium/',views.get_premium,name='get_premium'),
    path('random_number/',views.random,name='random_number'),
    path('admin/send/',views.SendAdminMessage.as_view(),name='send_admin_msg'),
    path('<str:slug>/',views.PostDetailView.as_view(),name='post_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interests/mainapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo, Post, Comment, Reply, SendMessageToAdmin,Message
from emoji_picker.widgets import EmojiPickerTextInput, EmojiPickerTextarea
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.forms.utils import flatatt
from django.utils.safestring import mark_safe

class DivTextWidget(forms.Textarea):
    def render(self, name, value, attrs=None,renderer=None):
        super().render(name, value, attrs)
        flat_attrs = flatatt(attrs)
        html = """
        <div contenteditable='true' id='%(id)s' name='text' role='textbox'></div>
        """ % {
            'attrs': flat_attrs,
            'id': attrs['id'],
        }
        return mark_safe(html)


class UserProfileInfoForms(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(
    attrs={'type': 'email',
           'placeholder':('Email')}))

    class Meta():
        model = User
        fields = ['username','first_name','last_name','email']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
            
            }


    def clean(self):
        cleaned_data = super(UserProfileInfoForms, self).clean()
        name = cleaned_data.get('username')
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')


class PostForm(forms.ModelForm):
    # text = forms.CharField(widget=DivTextWidget())
    class Meta():
        model = Post
        fields = ['title','text','group','image','file','tags','spoiler','NSFW','tag']
        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass text-title','placeholder':'Title'}),
            'text':forms.Textarea(attrs={'class':'textareaclass text-area-post','placeholder':'Post contents','id':'textareaclass'}),
        }

    def clean(self):
        cleaned_data = super(PostForm, self).clean()
        title = cleaned_data.get('title')
        text = cleaned_data.get('text')
        group = cleaned_data.get('group')
        image = cleaned_data.get('image')
        file = cleaned_data.get('file')
        tags = cleaned_data.get('tags')
        NSFW = cleaned_data.get('NSFW') 
        spoiler = cleaned_data.get('spoiler') 
        tag = cleaned_data.get('tag') 

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = ""
        self.fields['text'].label = ""
        self.fields['image'].label = ""
        self.fields['file'].label = ""
        self.fields['tags'].label = "Please select up to 5 interests"
        self.fields['NSFW'].label = "NSFW"
        self.fields['spoiler'].label = "Spoiler"
        self.fields['image'].required = False
        self.fields['file'].required = False

    
    
    
            
        # def clean_tags(self):
    #     tn = self.cleaned_data.get('tags', [])
    #     if len(tn) > 3:
    #         raise ValidationError('Invalid number of tags')

class AdminMessageForm(forms.ModelForm):
    class Meta():
        model = SendMessageToAdmin
        fields = ['title','text']

        def __init__(self,*args,**kwargs):
            super(AdminMessageForm,self).__str__(*args,**kwargs)

class MessageForm(forms.ModelForm):
    class Meta():
        model = Message
        fields = ['content']

        def clean(self):
            cleaned_data = super(MessageForm, self).clean()
            content = cleaned_data.get('content')

        def __init__(self,*args,**kwargs):
            super(Message,self).__str__(*args,**kwargs)
            self.fields['content'].label = ""

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ['text',]
        widgets = {
            'text':forms.Textarea(attrs={'class':'comment-from','placeholder':''}),
        }
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = ""

class ReplyForm(forms.ModelForm):
    class Meta():
        model = Reply
        fields = ['text']
        widgets = {
            'text':forms.Textarea(attrs={'class':'textareaclass','placeholder':''}),
        }
    def __init__(self, *args, **kwargs):
        super(ReplyForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = ""

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']
    
    def clean(self):
        cleaned_data = super(UserUpdateForm, self).clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ['image','description','gender','banner','tags','is_private','colour','website']
        widgets = {
            'description':forms.Textarea(attrs={'class':'textinputclass text-title','placeholder':'Title'}),
            # 'text':forms.Textarea(attrs={'class':'textareaclass textinputclass editable','placeholder':'Post Contents'}),
        }
    
    def clean(self):
        cleaned_data = super(ProfileUpdateForm, self).clean()
        image = cleaned_data.get('image')
        description = cleaned_data.get('description')
        gender = cleaned_data.get('gender')
        tags = cleaned_data.get('tags')
        is_private = cleaned_data.get('is_private')
        colour = cleaned_data.get('colour')
        website = cleaned_data.get('website')

interests/mainapp/templates/mainapp/_post.html
{% load static %}
{% load hitcount_tags %}
<div class="post-container">
<div class="post">
        
    <p>Posted by <a href="{% url 'mainapp:view_profile_with_pk' post.author.username %}"><strong title="{{ post.author.first_name }} {{ post.author.last_name }}">{{ post.author|safe|linebreaksbr|truncatechars_html:50 }}</strong></a>{% if post.author.userprofileinfo.verified %} <img draggable="false" title="Verified User" class="verifed" src="{% static 'images\verified.png' %}" alt="verified" width="15" height="15" srcset=""> {% endif %} {% if post.author.userprofileinfo.moderator %}<span title="Moderator" id="moderator">[M]</span>{% endif %} {{ post.published_date|timesince }} ago {% if post.group %}in <a href="{% url 'mainapp:single' slug=post.group.slug %}">{{ post.group.name }}</a>{% endif %}</p>
    <br>
    <!-- {% if hitcount.total_hits >= 50 %}
  <p title="This post has gained over 50 views, meaning it is trending" id="trending"><i class="fas fa-fire"></i> {{ hitcount.total_hits }} Views</p>
  {% else %}
  <p>{{ hitcount.total_hits }} Views</p>
  {% endif %} -->
  

    <h1><a title="View {{ post.title }}" class="title" href="{% url 'mainapp:post_detail' slug=post.slug %}">{{ post.title }}</a></h1>
    <div class="title-text-post-divider"></div>
    {% if post.NSFW %}<div class="nsfw"><p>NSFW</p></div> 
    
    <p><a id="readmore" href="{% url 'mainapp:post_detail' slug=post.slug %}">Read this NSFW Post&nbsp;<i class="fas fa-angle-right"></i></a></p>
    {% elif post.spoiler %}<div class="spoiler"><p>Spoiler</p></div> 
    <br>
    <p><a id="readmore" href="{% url 'mainapp:post_detail' slug=post.slug %}">Read this post which contains a spoiler&nbsp;<i class="fas fa-angle-right"></i></a></p>
    {% elif post.spoiler and post.NSFW %}<div class="nsfw"><p>NSFW</p></div> <div class="spoiler"><p>Spoiler</p></div> 
    <br>
    <p><a id="readmore" href="{% url 'mainapp:post_detail' slug=post.slug %}">Woah! This post is a double wammy of NSFW and has a spoiler! Proceed with care!&nbsp;<i class="fas fa-angle-right"></i></a></p>
    {% else %}
    {{ post.text|safe|linebreaksbr|truncatechars_html:50 }}
    <p><a id="readmore" href="{% url 'mainapp:post_detail' slug=post.slug %}">Read More&nbsp;<i class="fas fa-angle-right"></i></a></p>
    {% endif %}
    <br>
    <div class="tags-list-detail">
            {% for tag in post.tags.all|slice:"0:5" %}
            <a class="tag-list-a" href="{% url 'mainapp:tagged' tag.slug %}" class="tag-list-box"><button class="tag-list-style">{{ tag.name|safe|truncatechars_html:10 }}</button></a>&nbsp;&nbsp;
            <!-- <p id="tags-test">{{ tag.name|linebreaksbr }}</p>&nbsp;&nbsp; -->
            {% empty %}
            <li>No tags</li>
            {% endfor %}
        </div>
        <!-- |slice:"0:5" -->
    <br>
   
    
<br>
<a class="comment" title="View all {{ post.approve_comments.count }} comments" href="{% url 'mainapp:post_detail' slug=post.slug %}#comments">Comments: {{ post.approve_comments.count }}</a>
</div>
</div><br>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
<script>

function updateText(btn,newCount){
  btn.text(newCount + " " + verb)
}

$(".like-btn").click(function(e) {
  e.preventDefault()
  var this_ = $(this_)
  var likeUrl = this_.attr("data-href")
  var likeCount = parseInt(this_.attr("data-likes"))
  $.ajax({
    url: likeUrl,
    method: "GET",
    data: {},
    success: function(data){
      console.log(data)
      var newLikes;
      if (data.liked){
        newLikes = likeCount + 1
        //add like
        updateText(this_,newLikes, "Unlike")
      } else{
        newLikes = likeCount - 1
        //remove like
        updateText(this_,newLikes, "Like")
      }
    }, error: function(error){
      console.log(error)
      console.log("error")
    }
  })
})
</script>

interests/mainapp/templates/mainapp/message_form.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    
    {% for message in receiver_message_objects %}
        {% if message.sender == user %}
            <p>
                {{ message.content }}
                <i>{{ message.date_created|timesince }} ago</i>

                <a href="{% url 'mainapp:view_profile_with_pk' message.sender %}" id="message-link">{{ message.sender }}</a>
            </p>
        {% else %}
            <p>
                <a href="{% url 'mainapp:view_profile_with_pk' message.sender %}" id="message-link">{{ message.sender }}</a>
                <i>{{ message.date_created|timesince }} ago</i> {{ message.content }}
            </p>
        {% endif %}
    {% endfor %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.errors }}
        {{ form.content }}
        <button type="submit">Send</button>
    </form>
{% endblock %}

interests/mainapp/templates/mainapp/old_code.html
<!-- <a href="#" onClick="document.getElementById('likebutton').submit()">Like This Post</a> {{ post.likes }}   |   <a href="#" onClick="document.getElementById('dislikebutton').submit()">Dislike This Post</a> {{ post.dislikes }}
            <form id="likebutton" method="POST" action="/mainapp/{{ post.id }}/preference/1/">
              {% csrf_token %}
              <input type="hidden">
              </form>
              
              <form id="dislikebutton" method="POST" action="/mainapp/{{ post.id}}/preference/2/">
              {% csrf_token %}
              <input type="hidden">
              </form> -->
              <!-- <a href="/mainapp/{{ post.id }}/like" onClick="document.getElementById('likebutton').submit()">Like This Post</a> {{ post.likes }}
            <form id="likebutton" method="POST" action="/mainapp/{{ post.id }}/like">
              {% csrf_token %}
              <input type="hidden">
              </form> -->

interests/mainapp/templates/mainapp/oldprofile.html
{% load static %}

<div id="sidebar">
        <img draggable="false" style="border-radius: 50%; text-align: center; user-select: none; overflow: visible; margin: 0 auto; box-shadow: 0 0 0 12.25pt white;" class="header-profile-image" src="{{ username.userprofileinfo.image.url }}" alt="Profile Image">
        <div style="transform: translateY(-20%);" class="profile-info-profile">
      <h1 id="header-profile"><a style="color: #4287f4; text-decoration: none;" href="{% url 'mainapp:view_profile_with_pk' username %}">@{{ username }}</a>{% if username.userprofileinfo.verified %} <img style="user-select: none;" draggable="false" title="Verified User" class="verifed" src="{% static 'images\verified.png' %}" alt="verified" width="20" height="20" srcset=""> {% endif %} {% if user.userprofileinfo.moderator %}<span title="Moderator" id="moderator">[M]</span>{% endif %}</h1>
      <h2 id="header-profile">{{ username.first_name }} {{ username.last_name }}</h2>
      <h3 id="description-profile-page">{{ username.userprofileinfo.description }}</h3>
      <a id="message-user" href="{% url 'mainapp:message-form' username %}">
      <div id="message-user-div">
      <h4 id="description-profile-page"><i class="fas fa-comment"></i></h4>
      </div>
      </a>
      <br>
      <div class="tags-list-detail">
        {% for tag in username.userprofileinfo.tags.all %}
        <a style="user-select: none;" class="" href="{% url 'mainapp:tagged' tag.slug %}">
          <button style="background: {{ username.userprofileinfo.colour }};" class="tag-list-box-profile-profile profile-link">{{ tag.name|safe|linebreaksbr|truncatechars_html:10 }}</button>
          </a>
        
          {% empty %}
          <li style="user-select: none;">No tags</li>
          {% endfor %}
          </div>
          
          </div>
    </div>

interests/mainapp/templates/mainapp/post_draft_list.html
{% extends 'mainapp/base.html' %}

{% block content %}
{% for post in posts %}
    <div class="post">
        <p class="date">Create {{ post.created_date|date:'D-M-Y' }}</p>
        <h1><a href="{% url 'mainapp:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
        <p>{{post.text|truncatechars:200}}</p>
    </div>
{% endfor %}
{% endblock %}

interests/mainapp/templates/mainapp/post_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load humanize %}
{% load hitcount_tags %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% block pre_post_content %}
<div class="search-and-new-block">
<form class="search-form" action="{% url 'mainapp:search_results' %}" method="GET" value="{{request.GET.q}}">
    <input class="search-box" name="q" value="{{request.GET.q}}" type="text" placeholder="Search">
</form>
</div>

<!-- {% for tag in tags %}
<div class="tag-list">
    <li><a href="{% url 'mainapp:tagged' tag.slug %}">{{ tag.name }}</a></li>
{% empty %}
    <li>No tags</li>
</div>
{% endfor %} -->
<br><br><br>
<script>
    $(document).ready(function(){
      $("button").click(function(){
        $("#list-of-groups").toggle();
      });
    });
    </script>
<!-- <button>Toggle between hiding and showing the paragraphs</button>
<div class="list-of-groups">
{% if request.user.is_authenticated %}
<div class="group-list-home">
<h3>Your Groups</h3>
    {% for user_group in user_groups %}
    <li>
        <a href="{% url 'mainapp:single' slug=user_group.slug %}">{{ user_group.name }}</a>
    </li>
    {% endfor %}
    </div>
{% endif %}

<h3>All Groups</h3>
{# {% get_other_groups as other_groups %} #}
{% for group in all_groups %}
    <li><a href="{% url 'mainapp:single' slug=group.slug %}">{{ group.name }}</a></li>
{% endfor %}
</div> -->

{% endblock %}


{% block content %}
<div class="centercontent">
    {% for post in posts %}
    {% include 'mainapp/_post.html' %}
    {% endfor %}
    {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

</div> 


{% endblock %}

interests/mainapp/templates/mainapp/post_saved.html
{% extends 'mainapp/base.html' %}

{% block content %}
{% include 'mainapp/profile_header.html' %}

{% include 'mainapp/oldprofile.html' %}
    {% for post in posts %}
    <div class="content">
        {% include 'mainapp/_post.html' %}
    </div> 
    {% empty %}
    <div class="empty-text">
    <p>There doesn't seem to be anything here...</p>
    </div>
    {% endfor %}
    
{% endblock %}

interests/mainapp/templates/mainapp/profile-.html
{% extends 'mainapp/base.html' %}

{% load static %}
{% block content %}

{% csrf_token %}
<a href="{% url 'mainapp:get_premium' %}">
<button>Get premium</button>
</a>

{% endblock %}

interests/mainapp/templates/mainapp/profile_header.html
{% load static %}
<div style="background-size: cover; background-repeat:no-repeat; height: 45vh; background-image: url('{{ username.userprofileinfo.banner.url }}');" class="profile-header">

</div>
  

interests/mainapp/templates/mainapp/reply_form.html
{% extends 'mainapp/base.html' %}
{% block content %}
<h1>Reply</h1>
<form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="submitbtn">Reply</button>
</form>
{% endblock %}

interests/mainapp/templates/mainapp/search_reults.html
{% extends 'mainapp/base.html' %}
{% block content %}

<div class="search-container">
  <div style="margin-bottom: 2rem;" class="search-and-new-block">
  <h3 class="search-results-thing" id="center-stuff-search">Search results for <span class="search-thing"><strong style="">{{ request.GET.q }}</strong></span></h3>
  {% if object_list.count == 0 %}
  <h3 id="center-stuff-search">Sorry, no search results were found for {{ request.GET.q }}</h3>
  <a id="center-stuff-search" href="{% url 'mainapp:post_list' %}">Return home</a>
  {% endif %}
</div>
  {% for post in object_list %}
  {% include 'mainapp/_post.html' %}

{% empty %}



{% endfor %}


{% endblock %}

interests/mainapp/templates/mainapp/tags.html
{% extends 'mainapp/base.html' %}

{% block content %}
<div class="tags-list-tag-page">
    <h2>List of interests</h2>
{% for tag in tags %}
    <li><a href="{% url 'mainapp:tagged' tag.slug %}">{{ tag.name|safe }}</a></li>
{% empty %}
    <li>No tags</li>
{% endfor %}
</div>
{% endblock %}